/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.*;
import logica.Clases.*;
import utils.GuardaDatos;


public class EditarEvento extends javax.swing.JFrame {
    String idEventoSeleccionado;
    
    
    public EditarEvento(String IdEventoSeleccionado) {
        initComponents();
        this.idEventoSeleccionado = IdEventoSeleccionado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CONFIRMARBTN = new javax.swing.JButton();
        ATRASBTN = new javax.swing.JButton();
        horarioNuevo = new javax.swing.JComboBox<>();
        FechaLabel2 = new javax.swing.JLabel();
        FechaLabel = new javax.swing.JLabel();
        fechaNueva = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        tamañoNuevo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("EDITAR EVENTO SELECCIONADO");

        CONFIRMARBTN.setText("Confirmar");
        CONFIRMARBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONFIRMARBTNActionPerformed(evt);
            }
        });

        ATRASBTN.setText("Volver Atras");
        ATRASBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATRASBTNActionPerformed(evt);
            }
        });

        horarioNuevo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "14","15","16","17","18","19","20","21","22","23" }));
        horarioNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horarioNuevoActionPerformed(evt);
            }
        });

        FechaLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FechaLabel2.setForeground(new java.awt.Color(51, 51, 51));
        FechaLabel2.setText("Seleccione Horario");

        FechaLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        FechaLabel.setForeground(new java.awt.Color(51, 51, 51));
        FechaLabel.setText("Seleccione Fecha");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Seleccione Tamaño");

        tamañoNuevo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Futbol 5 - $22000 ", " Futbol 6 - $26000 ", " Futbol 7 - $43000 ", " Futbol 8 - $48000 "  }));
        tamañoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamañoNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(tamañoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel5)))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FechaLabel2)
                    .addComponent(horarioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(fechaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(FechaLabel)
                        .addGap(188, 188, 188))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(CONFIRMARBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(424, 424, 424))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(88, 88, 88)
                    .addComponent(ATRASBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(438, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaLabel2)
                    .addComponent(jLabel5)
                    .addComponent(FechaLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horarioNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tamañoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addComponent(CONFIRMARBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fechaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(333, Short.MAX_VALUE)
                    .addComponent(ATRASBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(37, 37, 37)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CONFIRMARBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONFIRMARBTNActionPerformed
        Pantalla newframe = new Pantalla();
        newframe.setVisible(true);
        newframe.setLocationRelativeTo(null);
        this.dispose();
        

        ListaEventos listaEventos = new ListaEventos();
        listaEventos.setListaEventos(GuardaDatos.cargarDatos());

        AlquilerCancha alquilerAModificar = listaEventos.obtenerEventoPorID(idEventoSeleccionado);
        alquilerAModificar.setTamañodecancha(tamañoNuevo.getSelectedItem().toString());
        alquilerAModificar.setHorario(horarioNuevo.getSelectedItem().toString());
        alquilerAModificar.setFecha(fechaNueva.getDate());

        GuardaDatos.guardarDatos(listaEventos.getListaEventos());

        

    }//GEN-LAST:event_CONFIRMARBTNActionPerformed

    private void ATRASBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATRASBTNActionPerformed
        ListaEventos listaEventos = new ListaEventos();
        listaEventos.setListaEventos(GuardaDatos.cargarDatos());
        EventosFuturos newframe = new EventosFuturos(listaEventos);
        newframe.setVisible(true);
        newframe.setLocationRelativeTo(null);
        this.dispose();        }//GEN-LAST:event_ATRASBTNActionPerformed

    private void horarioNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horarioNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horarioNuevoActionPerformed

    private void tamañoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamañoNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamañoNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ATRASBTN;
    private javax.swing.JButton CONFIRMARBTN;
    private javax.swing.JLabel FechaLabel;
    private javax.swing.JLabel FechaLabel2;
    private com.toedter.calendar.JDateChooser fechaNueva;
    private javax.swing.JComboBox<String> horarioNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> tamañoNuevo;
    // End of variables declaration//GEN-END:variables
}
